sudo: required
language: ruby
services:
  postgresql
addons:
  postgresql: 9.6
before_script:
  - cp spec/dummy/config/database.yml{.sample,}
  - psql -U postgres -c 'CREATE DATABASE storey_test;'
gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
rvm:
  - 2.4.1
  - 2.5.0
